### ISSUE TITLE
As a user, I'd like to have all pages auto-combined into a PDF for ease of reading

### ISSUE THREAD

**Issue by basicallyodd** [basicallyodd/twokinds-archiver#3]

**Comment by aaronfranke** [comment]
I don't know if per-chapter is possible, but that'd also be nice.

**Comment by basicallyodd** [comment]
@aaronfranke I like this idea, I've opened #4 for this

**Comment by basicallyodd** [comment]
basic pdf combining added in [fca6ff5](https://github.com/basicallyodd/twokinds-archiver/commit/fca6ff54b777419f3043f4dd7a3e6875813c7c0b)
